export const SET_ACTIVE_STEP_START = 'SET_ACTIVE_STEP_START';
export const SET_ACTIVE_STEP_SUCCESS = 'SET_ACTIVE_STEP_SUCCESS';
export const SET_ACTIVE_STEP_FAIL = 'SET_ACTIVE_STEP_FAIL';
export const RE_SET_ACTIVE_STEP_SUCCESS = 'RE_SET_ACTIVE_STEP_SUCCESS';

export const SET_USER_INFO_START = 'SET_USER_INFO_START';
export const SET_USER_INFO_SUCCESS = 'SET_USER_INFO_SUCCESS';
export const SET_USER_INFO_FAIL = 'SET_USER_INFO_FAIL';

export const SET_COMPANY_INFO_START = 'SET_COMPANY_INFO_START';
export const SET_COMPANY_INFO_SUCCESS = 'SET_COMPANY_INFO_SUCCESS';
export const SET_COMPANY_INFO_FAIL = 'SET_COMPANY_INFO_FAIL';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';